name: Build Artifacts

on:
  push:
    branches:
      - main
      - users/brandonmartinez/**
    paths:
      - ".github/workflows/**"
      - "src/**"

jobs:
  build-arm-json:
    name: Build ARM JSON
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Run Bicep Build
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            mkdir ./dist
            az bicep build --file src/SaaS.IaC/main.bicep --outfile ./dist/main.json
      - name: Copy Other Files
        run: |
          cp src/SaaS.IaC/createUiDefinition.json ./dist/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arm-json
          path: ./dist/**

  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: docker compose build
        run: |
          ls -la
          docker-compose build

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build-arm-json
      - build-application
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: arm-json
          path: ./dist/
      - name: Create Release with Artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Generated Latest Release"
          files: |
            ./dist/**
