name: Hugo Docs Build - GH Pages

on:
  push:
    branches:
      - docs-updates
    paths:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        working-directory: docs/azure-saas-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/docs-updates'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public