on:
  workflow_call:
      inputs:
        image_to_push:
          required: true
          type: string
        tag_name:
          required: true
          type: string
        tag_latest:
          required: false
          type: boolean
          default: false

name: Container Image Publishing - Build

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build Docker Image
        run: |
          docker-compose build ${{ inputs.image_to_push }}

      - name: Create Tag
        run: |
          GH_IMAGE_PATH="ghcr.io/${{ github.repository }}/${{ inputs.image_to_push }}"
          GH_TAG=$GH_IMAGE_PATH:${{ inputs.tag_name }}
          # Make characters lowercase
          GH_TAG=$(echo $GH_TAG | tr '[:upper:]' '[:lower:]')
          echo "Tagging ${{ inputs.image_to_push }} with $GH_TAG in GitHub Container Registry"
          docker tag ${{ inputs.image_to_push }} $GH_TAG
        
      - name: Tag Latest
        if: ${{ inputs.tag_latest }}
        run: |
          GH_TAG_LATEST=$GH_IMAGE_PATH:latest
          # Make characters lowercase
          GH_TAG_LATEST=$(echo $GH_TAG_LATEST | tr '[:upper:]' '[:lower:]')
          echo "Tagging ${{ inputs.image_to_push }} with $GH_TAG_LATEST in GitHub Container Registry"
          docker tag ${{ inputs.image_to_push }} $GH_TAG_LATEST
        
      - name: Publish Image
        run: | 
          echo "Pushing ${{ inputs.image_to_push }} to GitHub Container Registry"
          docker push --all-tags $GH_IMAGE_PATH